# Configuration for ANSTO two filter radon detector
# Basic config, one 1500 L detector

detectors:
  - detector_kind: "L1500"
    serial_port: "serial:/dev/ttyUSB0:115200"
    name: "TEST-002M"
    datalogger_serial: -1

calbox:
  kind: "generic"
  # The labjack ID can be set in software.  A special value of -1 means
  # to use the first labjack found, which only makes sense if there is
  # only ever one labjack connected to the PC
  labjack_id: -1
  # Only use the labjack with the serial number specifed here.  A special
  # value of -1 means to ignore the serial number.
  labjack_serial: -1
  # Flushing duration to use during calibrations (seconds)
  flush_duration_sec: 3600
  # Radon injection duration to use during calibrations (seconds)
  inject_duration_sec: 3600
  # Duration to switch to background mode for background charactisation (seconds)
  background_duration_sec: 3600

# allowed log levels (from least output to most):
# CRITICAL, ERROR, WARNING, INFO, DEBUG
loglevel: "DEBUG"
